export const GETCONTACT = "GETCONTACT";
export const DELETECONTACT = "DELETECONTACT";
export const ADDCONTACT = "ADDCONTACT";
export const DETAILCONTACT = "DETAILCONTACT";
export const EDITCONTACT = "EDITCONTACT";
